### ISSUE TITLE
Using fixed position for the background div

### ISSUE THREAD

**Issue by moeenio** [Pufflegamerz/pufflegamerz.github.io#4]
For the div that makes the background, you could use `position: fixed`; and `z-index: -1`. And for placing the text, you can use a flexbox on `#text` that is full width and height with correct alignement properties.

**Comment by petabyt** [comment]
Setting the background div to fixed does nothing for me.

**Comment by moeenio** [comment]
Gonna do a PR.

**Comment by moeenio** [comment]
You should indeed add the top and bottom placement

**Comment by moeenio** [comment]
Wait, did you just update the site ? My suggestion was applying to when there wasn't the extended info when scrolling
